/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Example;

import java.awt.Color;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author NEW
 */
public class CBT extends javax.swing.JFrame {
    
     String[] Questions = {"1. Who should have won the Ballon'Dor?",
         "2. Whose fault was it? ",
         "3. 5 + 6",
         "4. 5 * 2",
         "5. 7 - 3",
         "6. 10 / 2"
       };
     String[] optionA = {"Haaland",
         "Karol",
         "4",
         "5",
         "6",
         "7"
       };
     String[] optionB = {"Messi",
         "Ise",
         "11",
         "4",
         "50",
         "80"
       };
     String[] optionC = {"Rodri",
         "Safe",
         "40",
         "10",
         "44",
         "5"
       };
     String[] optionD = {"Mbappe",
         "safety",
         "11",
         "50",
         "4",
         "80"
       };
     String[] Answer = {"Haaland",
         "Karol",
         "11",
         "10",
         "4",
         "5"
       };
     String[] yourAnswer = {"",
         "",
         "",
         "",
         "",
         ""
       };
     int i = 0;
     String yourOption = "";
     int score = 0;
    

    /**
     * Creates new form CBT
     */
    public CBT() {
        initComponents();
        jTextArea1.setText(Questions[i]);
        jRadioButton1.setText(optionA[i]);
        jRadioButton2.setText(optionB[i]);
        jRadioButton3.setText(optionC[i]);
        jRadioButton4.setText(optionD[i]);
        time t = new time();
        Thread t1 = new Thread(t);
        t1.start();
        
        blink b = new blink();
        Thread b1 = new Thread(b);
        b1.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Computer Based Test");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Previous");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton4");

        jButton4.setText("Calculator");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(75, 75, 75)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(i==0){
    JOptionPane.showMessageDialog(rootPane, "This is the first question");
}else{
    if(jRadioButton1.isSelected()){
    yourOption = jRadioButton1.getText();
    yourAnswer[i] = yourOption;
    }else if(jRadioButton2.isSelected()){
    yourOption = jRadioButton2.getText();
    yourAnswer[i] = yourOption;
    }else if(jRadioButton3.isSelected()){
    yourOption = jRadioButton3.getText();
    yourAnswer[i] = yourOption;
    }else if(jRadioButton4.isSelected()){
    yourOption = jRadioButton4.getText();
    yourAnswer[i] = yourOption;
    }
    
        --i;
        buttonGroup1.clearSelection();
        
        jTextArea1.setText(Questions[i]);
        jRadioButton1.setText(optionA[i]);
        jRadioButton2.setText(optionB[i]);
        jRadioButton3.setText(optionC[i]);
        jRadioButton4.setText(optionD[i]);
        yourOption = yourAnswer[i];
        if(yourOption.equals(jRadioButton1.getText())){
            jRadioButton1.setSelected(true);
        }else if(yourOption.equals(jRadioButton2.getText())){
            jRadioButton2.setSelected(true);
        }else if(yourOption.equals(jRadioButton3.getText())){
            jRadioButton3.setSelected(true);
        }else if(yourOption.equals(jRadioButton4.getText())){
            jRadioButton4.setSelected(true);
        }
        
// TODO add your handling code here:
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

if(i < Questions.length-1){
    if(jRadioButton1.isSelected()){
    yourOption = jRadioButton1.getText();
    yourAnswer[i] = yourOption;
    }else if(jRadioButton2.isSelected()){
    yourOption = jRadioButton2.getText();
    yourAnswer[i] = yourOption;
    }else if(jRadioButton3.isSelected()){
    yourOption = jRadioButton3.getText();
    yourAnswer[i] = yourOption;
    }else if(jRadioButton4.isSelected()){
    yourOption = jRadioButton4.getText();
    yourAnswer[i] = yourOption;
    }
     ++i;
        jTextArea1.setText(Questions[i]);
        jRadioButton1.setText(optionA[i]);
        jRadioButton2.setText(optionB[i]);
        jRadioButton3.setText(optionC[i]);
        jRadioButton4.setText(optionD[i]);
        buttonGroup1.clearSelection();
        yourOption = yourAnswer[i];
         if(yourOption.equals(jRadioButton1.getText())){
            jRadioButton1.setSelected(true);
        }else if(yourOption.equals(jRadioButton2.getText())){
            jRadioButton2.setSelected(true);
        }else if(yourOption.equals(jRadioButton3.getText())){
            jRadioButton3.setSelected(true);
        }else if(yourOption.equals(jRadioButton4.getText())){
            jRadioButton4.setSelected(true);
        }
        
    
}else{
       
        JOptionPane.showMessageDialog(rootPane, "This is the last question");
        // TODO add your handling code here:
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   /*String text ="";   
for(int i = 0; i<yourAnswer.length; i++){
    text = text + yourAnswer[i]+"\n";
    jTextArea1.setText(text);
}
for(int i = 0; i<yourAnswer.length; i++){
if(yourAnswer[i] == Answer[i]){
    score += 1;
}else{
    score = score;
}

jLabel3.setText("Score: " + Integer.toString(score));
}*/
    if(jRadioButton1.isSelected()){
    yourOption = jRadioButton1.getText();
    yourAnswer[i] = yourOption;
    }else if(jRadioButton2.isSelected()){
    yourOption = jRadioButton2.getText();
    yourAnswer[i] = yourOption;
    }else if(jRadioButton3.isSelected()){
    yourOption = jRadioButton3.getText();
    yourAnswer[i] = yourOption;
    }else if(jRadioButton4.isSelected()){
    yourOption = jRadioButton4.getText();
    yourAnswer[i] = yourOption;
    }
    String yanswer = "";
    String canswer = "";
    for(int i = 0; i<Questions.length-1; i++){
    yanswer = yourAnswer[i];
    canswer = Answer[i];
    if(canswer.equals(yanswer)){
     score++;
    }
            }
    
    JOptionPane.showMessageDialog(rootPane,"Your score is " + score);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
    Runtime.getRuntime().exec("calc");
            }catch (Exception e){
}      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public class time implements Runnable{
        @Override
        public void run(){
            try{
            for (int i = 1; i<2; i--){
                Date date = new Date();
                jLabel4.setText(date.toString());
                TimeUnit.SECONDS.sleep(1);
            }
            }catch(Exception e){
                System.out.println("error");
            }
        }

}
    public class blink implements Runnable{
        @Override
        public void run(){
            try{
            for (int i = 1; i<2; i--){
                
                jLabel4.setForeground(Color.red);
                TimeUnit.SECONDS.sleep(1);
                jLabel4.setForeground(Color.BLUE);
                TimeUnit.SECONDS.sleep(1);
                jLabel4.setForeground(Color.orange);
                TimeUnit.SECONDS.sleep(1);
                jLabel4.setForeground(Color.cyan);
                TimeUnit.SECONDS.sleep(1);
                jLabel4.setForeground(Color.black);
                TimeUnit.SECONDS.sleep(1);
                jLabel4.setForeground(Color.green);
                TimeUnit.SECONDS.sleep(1);
            }
            }catch(Exception e){
                System.out.println("error");
            }
        }

}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CBT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CBT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CBT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CBT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CBT().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
